# Generated by Django 5.2.10 on 2026-01-28 15:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benevole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(blank=True, help_text='Adresse email du bénévole', max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=200, verbose_name='Adresse complète')),
                ('arrondissement', models.CharField(blank=True, max_length=10, verbose_name='Arrondissement')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('disponibilite', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('inactif', 'Inactif')], default='disponible', max_length=20, verbose_name='Disponibilité')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Bénévole',
                'verbose_name_plural': 'Bénévoles',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='core_benevo_nom_dd71c4_idx'), models.Index(fields=['disponibilite'], name='core_benevo_disponi_673c5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de famille de l'élève", max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('classe', models.CharField(blank=True, help_text='Exemple : CE2, 6ème, 2nde', max_length=50, verbose_name='Classe')),
                ('adresse', models.CharField(blank=True, max_length=200, verbose_name='Adresse complète')),
                ('arrondissement', models.CharField(blank=True, help_text='Exemple : 13009', max_length=10, verbose_name='Arrondissement')),
                ('latitude', models.FloatField(blank=True, help_text='Coordonnée GPS pour la carte', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, help_text='Coordonnée GPS pour la carte', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('statut', models.CharField(choices=[('accompagne', 'Accompagné'), ('a_accompagner', 'À accompagner'), ('en_attente', 'En attente')], default='a_accompagner', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='core_eleve_nom_ef63e9_idx'), models.Index(fields=['statut'], name='core_eleve_statut_f22120_idx')],
            },
        ),
        migrations.CreateModel(
            name='Binome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text="Date de début de l'accompagnement", verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text="Date de fin de l'accompagnement (si terminé)", null=True, verbose_name='Date de fin')),
                ('notes', models.TextField(blank=True, help_text="Remarques sur l'accompagnement", verbose_name='Notes')),
                ('actif', models.BooleanField(default=True, verbose_name='Binôme actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('benevole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binomes', to='core.benevole', verbose_name='Bénévole')),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binome', to='core.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Binôme',
                'verbose_name_plural': 'Binômes',
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('eleve',), name='unique_active_binome_per_eleve')],
            },
        ),
    ]
