# Generated by Django 4.2.27 on 2026-02-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eleve',
            name='core_eleve_nom_ef63e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='eleve',
            name='core_eleve_statut_f22120_idx',
        ),
        migrations.AddField(
            model_name='eleve',
            name='etablissement',
            field=models.CharField(blank=True, help_text="Nom de l'école, collège ou lycée", max_length=200, verbose_name='Établissement scolaire'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='informations_complementaires',
            field=models.TextField(blank=True, help_text='Toute information utile (besoins spécifiques, disponibilités, etc.)', verbose_name='Informations complémentaires'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='matieres_souhaitees',
            field=models.TextField(blank=True, help_text="Matières pour lesquelles l'élève a besoin d'aide (ex: Mathématiques, Français, Anglais)", verbose_name='Matières souhaitées'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='nom_parent',
            field=models.CharField(blank=True, help_text='Nom de famille du parent/tuteur légal', max_length=100, verbose_name='Nom du parent'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='prenom_parent',
            field=models.CharField(blank=True, help_text='Prénom du parent/tuteur légal', max_length=100, verbose_name='Prénom du parent'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='telephone',
            field=models.CharField(blank=True, help_text="Numéro de téléphone personnel de l'élève", max_length=20, verbose_name="Téléphone de l'élève"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='telephone_parent',
            field=models.CharField(blank=True, help_text='Numéro de téléphone principal des parents', max_length=20, verbose_name='Téléphone des parents'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='arrondissement',
            field=models.CharField(blank=True, help_text='Ex: 1er, 2e, 3e, etc.', max_length=10, verbose_name='Arrondissement'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.CharField(blank=True, choices=[('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('2de', '2de'), ('1re', '1re'), ('Terminale', 'Terminale'), ('CAP', 'CAP'), ('ULIS', 'ULIS')], max_length=50, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('accompagne', 'Accompagné'), ('a_accompagner', 'À accompagner'), ('en_attente', 'En attente'), ('archive', 'Archivé')], default='a_accompagner', max_length=20, verbose_name='Statut'),
        ),
    ]
