# Generated by Django 4.2.27 on 2026-02-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_eleve_core_eleve_nom_ef63e9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la matière')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Matière active')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='matieres_souhaitees',
        ),
        migrations.AddField(
            model_name='eleve',
            name='matieres_souhaitees',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez une ou plusieurs matières', related_name='eleves', to='core.matiere', verbose_name='Matières souhaitées'),
        ),
    ]
