# Generated by Django 4.2.27 on 2026-02-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_matiere_remove_eleve_matieres_souhaitees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='code_postal',
            field=models.CharField(blank=True, help_text='Ex: 13001, 13008', max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='ville',
            field=models.CharField(blank=True, help_text='Ex: Marseille, Aix-en-Provence', max_length=100, verbose_name='Ville'),
        ),
    ]
