# Generated by Django 4.2.27 on 2026-02-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eleve_code_postal_eleve_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='numero_rue',
            field=models.CharField(blank=True, help_text='Numéro de rue (ex: 12, 12 bis, 12 ter)', max_length=20, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='adresse',
            field=models.CharField(blank=True, help_text='Ex: Rue de la République, Avenue du Prado', max_length=200, verbose_name='Nom de la rue'),
        ),
    ]
