# Generated by Django 4.2.27 on 2026-02-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_eleve_numero_rue_alter_eleve_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='statut_saisie',
            field=models.CharField(choices=[('brouillon', 'Brouillon (saisie en cours)'), ('complet', 'Complet (validé)')], default='brouillon', help_text='Brouillon = saisie en cours, Complet = fiche validée', max_length=20, verbose_name='Statut de saisie'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('accompagne', 'Accompagné'), ('a_accompagner', 'À accompagner'), ('en_attente', 'En attente'), ('archive', 'Archivé')], default='a_accompagner', max_length=20, verbose_name="Statut d'accompagnement"),
        ),
    ]
