# Generated by Django 4.2.27 on 2026-02-08 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eleve_statut_saisie_alter_eleve_statut'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='benevole',
            name='core_benevo_disponi_673c5c_idx',
        ),
        migrations.RemoveField(
            model_name='benevole',
            name='arrondissement',
        ),
        migrations.RemoveField(
            model_name='benevole',
            name='disponibilite',
        ),
        migrations.AddField(
            model_name='benevole',
            name='a_donne_photo',
            field=models.CharField(blank=True, help_text='oui/non - Photo fournie', max_length=10, verbose_name='A donné photo'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='code_postal',
            field=models.CharField(blank=True, help_text='Exemple : 13001, 13190', max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='college',
            field=models.CharField(blank=True, help_text='oui/non - Peut accompagner niveau collège', max_length=10, verbose_name='Collège'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='commentaires',
            field=models.TextField(blank=True, help_text='Remarques et informations diverses', verbose_name='Commentaires'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='divers',
            field=models.TextField(blank=True, help_text='Autres informations', verbose_name='Divers'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='est_ajoute_au_groupe_whatsapp',
            field=models.CharField(blank=True, help_text='oui/non - Ajouté au groupe WhatsApp', max_length=10, verbose_name='Groupe WhatsApp'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='est_responsable',
            field=models.CharField(blank=True, help_text='oui/non - Indique si la personne est responsable', max_length=10, verbose_name='Est responsable'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='extranet',
            field=models.CharField(blank=True, help_text='oui/non - Accès extranet créé', max_length=10, verbose_name='Extranet'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='fichier',
            field=models.CharField(blank=True, help_text='oui/non - Dossier administratif complet', max_length=10, verbose_name='Fichier'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='lycee',
            field=models.CharField(blank=True, help_text='oui/non - Peut accompagner niveau lycée', max_length=10, verbose_name='Lycée'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='matieres',
            field=models.TextField(blank=True, help_text='Matières que le bénévole peut enseigner', verbose_name='Matières'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='moyen_deplacement',
            field=models.CharField(blank=True, help_text='Exemple : Véhicule personnel, Transport en commun', max_length=100, verbose_name='Moyen de déplacement'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='outlook',
            field=models.CharField(blank=True, help_text='oui/non - Ajouté dans Outlook', max_length=10, verbose_name='Outlook'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='primaire',
            field=models.CharField(blank=True, help_text='oui/non - Peut accompagner niveau primaire', max_length=10, verbose_name='Primaire'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='profession',
            field=models.CharField(blank=True, help_text='Profession actuelle ou passée', max_length=200, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='reunion_accueil_faite',
            field=models.CharField(blank=True, help_text="Date ou statut de la réunion d'accueil (0, 1, date)", max_length=50, verbose_name="Réunion d'accueil"),
        ),
        migrations.AddField(
            model_name='benevole',
            name='statut',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Disponible', 'Disponible'), ('Indisponible', 'Indisponible')], default='Disponible', help_text='Statut actuel du bénévole', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='ville',
            field=models.CharField(blank=True, help_text='Exemple : Marseille, Allauch', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='volet_3_casier_judiciaire',
            field=models.CharField(blank=True, help_text='Date de réception du volet 3', max_length=50, verbose_name='Volet 3 casier judiciaire'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='zone_geographique',
            field=models.CharField(blank=True, help_text="Zone d'intervention préférée", max_length=200, verbose_name='Zone géographique'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text="Date d'ajout dans le système", verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, help_text='Dernière mise à jour de la fiche', verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordonnée GPS pour la carte', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordonnée GPS pour la carte', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='nom',
            field=models.CharField(help_text='Nom de famille du bénévole', max_length=100, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='telephone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddIndex(
            model_name='benevole',
            index=models.Index(fields=['statut'], name='core_benevo_statut_dc493d_idx'),
        ),
        migrations.AddIndex(
            model_name='benevole',
            index=models.Index(fields=['code_postal'], name='core_benevo_code_po_0acdd8_idx'),
        ),
    ]
