# Generated by Django 4.2.27 on 2026-02-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_benevole_core_benevo_disponi_673c5c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benevole',
            name='a_donne_photo',
            field=models.BooleanField(default=False, help_text='Photo fournie', verbose_name='A donné photo'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='college',
            field=models.BooleanField(default=False, help_text='Peut accompagner niveau collège', verbose_name='Collège'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='est_ajoute_au_groupe_whatsapp',
            field=models.BooleanField(default=False, help_text='Ajouté au groupe WhatsApp', verbose_name='Groupe WhatsApp'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='est_responsable',
            field=models.BooleanField(default=False, help_text="Indique si la personne est responsable dans l'association", verbose_name='Est responsable'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='extranet',
            field=models.BooleanField(default=False, help_text='Accès extranet créé', verbose_name='Extranet'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='fichier',
            field=models.BooleanField(default=False, help_text='Dossier administratif complet', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='lycee',
            field=models.BooleanField(default=False, help_text='Peut accompagner niveau lycée', verbose_name='Lycée'),
        ),
        migrations.RemoveField(
            model_name='benevole',
            name='matieres',
        ),
        migrations.AlterField(
            model_name='benevole',
            name='outlook',
            field=models.BooleanField(default=False, help_text='Ajouté dans Outlook', verbose_name='Outlook'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='primaire',
            field=models.BooleanField(default=False, help_text='Peut accompagner niveau primaire', verbose_name='Primaire'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='reunion_accueil_faite',
            field=models.BooleanField(default=False, help_text="A participé à la réunion d'accueil", verbose_name="Réunion d'accueil faite"),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='volet_3_casier_judiciaire',
            field=models.CharField(blank=True, help_text='Date de réception du volet 3 (ou laissez vide)', max_length=50, verbose_name='Volet 3 casier judiciaire'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='ordre',
            field=models.IntegerField(default=0, help_text="Pour trier les matières dans l'ordre souhaité", verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='benevole',
            name='matieres',
            field=models.ManyToManyField(blank=True, help_text='Matières que le bénévole peut enseigner (choix multiples)', related_name='benevoles', to='core.matiere', verbose_name='Matières enseignées'),
        ),
    ]
