# Generated by Django 4.2.27 on 2026-02-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_benevole_a_donne_photo_alter_benevole_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='complement_adresse',
            field=models.CharField(blank=True, help_text='Ex: Bâtiment A, 3ème étage, appartement 12', max_length=200, verbose_name="Complément d'adresse"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='date_derniere_visite',
            field=models.DateField(blank=True, help_text='Date de la dernière visite effectuée chez la famille', null=True, verbose_name='Date de dernière visite'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='email_parent',
            field=models.EmailField(blank=True, help_text='Adresse email de contact des parents', max_length=254, verbose_name='Email des parents'),
        ),
    ]
