# Generated by Django 4.2.27 on 2026-02-09 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_eleve_complement_adresse_eleve_date_derniere_visite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='co_responsable',
            field=models.ForeignKey(blank=True, help_text='Utilisateur en charge de cet élève', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_geres', to=settings.AUTH_USER_MODEL, verbose_name='Co-responsable'),
        ),
    ]
