# Generated by Django 4.2.27 on 2026-02-09 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_eleve_co_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Associer ce bénévole à un utilisateur Django', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benevole', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
    ]
