# Generated by Django 4.2.27 on 2026-02-09 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_profilutilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benevole',
            name='user',
        ),
        migrations.AddField(
            model_name='benevole',
            name='co_responsable',
            field=models.ForeignKey(blank=True, help_text='Utilisateur en charge de ce bénévole', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benevoles_geres', to=settings.AUTH_USER_MODEL, verbose_name='Co-responsable'),
        ),
    ]
