# Generated by Django 4.2.27 on 2026-02-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_benevole_user_benevole_co_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='date_contact',
            field=models.CharField(blank=True, help_text='Date du premier contact (format libre)', max_length=50, null=True, verbose_name='Date du contact'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='disponibilites_competences',
            field=models.TextField(blank=True, help_text='Détails sur les disponibilités et compétences du candidat', null=True, verbose_name='Disponibilités et compétences'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='informations_complementaires',
            field=models.TextField(blank=True, help_text='Informations supplémentaires sur le candidat', null=True, verbose_name='Informations complémentaires'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='origine_contact',
            field=models.CharField(blank=True, help_text='Source du contact (JVA, site ESA, Maison des associations, etc.)', max_length=100, null=True, verbose_name='Origine du contact'),
        ),
    ]
