# Generated by Django 4.2.27 on 2026-02-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_benevole_date_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='numero_rue',
            field=models.CharField(blank=True, help_text='Numéro de rue (ex: 12, 12 bis, 12 ter)', max_length=20, verbose_name='Numéro'),
        ),
    ]
