# Generated by Django 4.2.27 on 2026-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_benevole_numero_rue'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='arrondissement',
            field=models.CharField(blank=True, help_text='Ex: 1er, 2e, 3e, etc.', max_length=10, verbose_name='Arrondissement'),
        ),
    ]
