# Generated by Django 5.2.11 on 2026-02-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_benevole_arrondissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benevole',
            name='adresse',
            field=models.CharField(blank=True, max_length=500, verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='adresse',
            field=models.CharField(blank=True, help_text='Ex: Rue de la République, Avenue du Prado', max_length=500, verbose_name='Nom de la rue'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='complement_adresse',
            field=models.CharField(blank=True, help_text='Ex: Bâtiment A, 3ème étage, appartement 12', max_length=500, verbose_name="Complément d'adresse"),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='etablissement',
            field=models.CharField(blank=True, help_text="Nom de l'école, collège ou lycée", max_length=500, verbose_name='Établissement scolaire'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone_parent',
            field=models.CharField(blank=True, help_text='Numéro de téléphone principal des parents', max_length=50, verbose_name='Téléphone des parents'),
        ),
    ]
