# Generated by Django 5.2.11 on 2026-04-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_benevole_adresse_alter_eleve_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benevole',
            name='volet_3_casier_judiciaire',
            field=models.CharField(blank=True, help_text='Date de réception du volet 3 (ou laissez vide)', max_length=50, null=True, verbose_name='Volet 3 casier judiciaire'),
        ),
    ]
