# Generated by Django 5.2.11 on 2026-04-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_benevole_volet_3_casier_judiciaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benevole',
            name='arrondissement',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='arrondissement',
        ),
    ]
